targets:
  $default:
    builders:
      graphql_codegen:
        options:
          schema: lib/graphql/schema.graphql
          output_dir: lib/graphql
          documents:
            - lib/graphql/authenticate.graphql
            - lib/graphql/banner.graphql
            - lib/graphql/cart.graphql
            - lib/graphql/Customer.graphql
            - lib/graphql/order.graphql
            - lib/graphql/product.graphql
            - lib/graphql/app_update.graphql
            - lib/graphql/loyalty_points_config.graphql
          scalars:
            DateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
            Money:
              type: double
          clients:
            - graphql_flutter