#!/bin/bash

# Script to remove generated splash screen files
# This should be run after flutter clean to remove files generated by flutter_native_splash

echo "Cleaning generated splash screen files..."

# Android splash files
ANDROID_RES_DIR="android/app/src/main/res"

# Remove splash.png files from all drawable directories
find "$ANDROID_RES_DIR" -name "splash.png" -type f -delete
echo "  ✓ Removed splash.png files"

# Remove android12splash.png files
find "$ANDROID_RES_DIR" -name "android12splash.png" -type f -delete
echo "  ✓ Removed android12splash.png files"

# Remove splash_scaled.xml
find "$ANDROID_RES_DIR" -name "splash_scaled.xml" -type f -delete
echo "  ✓ Removed splash_scaled.xml files"

# Remove generated background.png files (only if they're generated by flutter_native_splash)
# Note: Be careful not to delete custom background.png files
# These are typically in drawable, drawable-v21, drawable-night, drawable-night-v21
if [ -f "$ANDROID_RES_DIR/drawable/background.png" ]; then
    rm -f "$ANDROID_RES_DIR/drawable/background.png"
    echo "  ✓ Removed drawable/background.png"
fi
if [ -f "$ANDROID_RES_DIR/drawable-v21/background.png" ]; then
    rm -f "$ANDROID_RES_DIR/drawable-v21/background.png"
    echo "  ✓ Removed drawable-v21/background.png"
fi
if [ -f "$ANDROID_RES_DIR/drawable-night/background.png" ]; then
    rm -f "$ANDROID_RES_DIR/drawable-night/background.png"
    echo "  ✓ Removed drawable-night/background.png"
fi
if [ -f "$ANDROID_RES_DIR/drawable-night-v21/background.png" ]; then
    rm -f "$ANDROID_RES_DIR/drawable-night-v21/background.png"
    echo "  ✓ Removed drawable-night-v21/background.png"
fi

# Restore launch_background.xml files to default state (remove splash references)
if [ -f "$ANDROID_RES_DIR/drawable/launch_background.xml" ]; then
    if grep -q "@drawable/splash" "$ANDROID_RES_DIR/drawable/launch_background.xml" 2>/dev/null; then
        cat > "$ANDROID_RES_DIR/drawable/launch_background.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" />
</layer-list>
EOF
        echo "  ✓ Restored drawable/launch_background.xml to default"
    fi
fi

if [ -f "$ANDROID_RES_DIR/drawable-night/launch_background.xml" ]; then
    if grep -q "@drawable/splash" "$ANDROID_RES_DIR/drawable-night/launch_background.xml" 2>/dev/null; then
        cat > "$ANDROID_RES_DIR/drawable-night/launch_background.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/black" />
</layer-list>
EOF
        echo "  ✓ Restored drawable-night/launch_background.xml to default"
    fi
fi

if [ -f "$ANDROID_RES_DIR/drawable-v21/launch_background.xml" ]; then
    if grep -q "@drawable/splash" "$ANDROID_RES_DIR/drawable-v21/launch_background.xml" 2>/dev/null; then
        cat > "$ANDROID_RES_DIR/drawable-v21/launch_background.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" />
</layer-list>
EOF
        echo "  ✓ Restored drawable-v21/launch_background.xml to default"
    fi
fi

if [ -f "$ANDROID_RES_DIR/drawable-night-v21/launch_background.xml" ]; then
    if grep -q "@drawable/splash" "$ANDROID_RES_DIR/drawable-night-v21/launch_background.xml" 2>/dev/null; then
        cat > "$ANDROID_RES_DIR/drawable-night-v21/launch_background.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/black" />
</layer-list>
EOF
        echo "  ✓ Restored drawable-night-v21/launch_background.xml to default"
    fi
fi

# Remove generated launch_logo.png files
find "$ANDROID_RES_DIR" -name "launch_logo.png" -type f -delete
echo "  ✓ Removed launch_logo.png files"

# iOS splash files
IOS_RUNNER_DIR="ios/Runner"

# Remove LaunchImage.imageset contents (generated by flutter_native_splash)
if [ -d "$IOS_RUNNER_DIR/Assets.xcassets/LaunchImage.imageset" ]; then
    rm -rf "$IOS_RUNNER_DIR/Assets.xcassets/LaunchImage.imageset"
    echo "  ✓ Removed iOS LaunchImage.imageset"
fi

# Remove LaunchBackground.imageset contents (generated by flutter_native_splash)
if [ -d "$IOS_RUNNER_DIR/Assets.xcassets/LaunchBackground.imageset" ]; then
    rm -rf "$IOS_RUNNER_DIR/Assets.xcassets/LaunchBackground.imageset"
    echo "  ✓ Removed iOS LaunchBackground.imageset"
fi

echo ""
echo "Splash screen cleanup complete!"
echo "Run 'dart run flutter_native_splash:create' to regenerate splash screens."

