#!/bin/bash
# Script to fix namespace and v1 embedding issues in Flutter plugins
# Run this after 'flutter pub get' if build fails

echo "🔧 Fixing Flutter plugin issues..."

# Remove plugins that fail Android Kotlin compile (v1 embedding / Registrar issues).
# Flutter reads from BOTH .flutter-plugins AND .flutter-plugins-dependencies (JSON).
FLUTTER_PLUGINS=".flutter-plugins"
if [ -f "$FLUTTER_PLUGINS" ]; then
  if grep -qE '^(fluttertoast|speech_to_text|flutter_dynamic_icon)=' "$FLUTTER_PLUGINS"; then
    echo "  ✅ Removing fluttertoast, speech_to_text, and flutter_dynamic_icon from .flutter-plugins..."
    grep -vE '^(fluttertoast|speech_to_text|flutter_dynamic_icon)=' "$FLUTTER_PLUGINS" > "${FLUTTER_PLUGINS}.tmp" && mv "${FLUTTER_PLUGINS}.tmp" "$FLUTTER_PLUGINS"
  fi
fi
if [ -f .flutter-plugins-dependencies ]; then
  if grep -qE '"name":"(fluttertoast|speech_to_text|flutter_dynamic_icon)"' .flutter-plugins-dependencies; then
    echo "  ✅ Removing fluttertoast, speech_to_text, and flutter_dynamic_icon from .flutter-plugins-dependencies..."
    jq '
      .plugins.android |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .plugins.ios |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .plugins.web |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .plugins.macos |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .plugins.linux |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .plugins.windows |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .dependencyGraph |= map(select(.name != "fluttertoast" and .name != "speech_to_text" and .name != "flutter_dynamic_icon")) |
      .dependencyGraph |= map(if .dependencies then .dependencies |= map(select(. != "fluttertoast" and . != "speech_to_text" and . != "flutter_dynamic_icon")) else . end)
    ' .flutter-plugins-dependencies > .flutter-plugins-dependencies.tmp && mv .flutter-plugins-dependencies.tmp .flutter-plugins-dependencies
    echo "     fluttertoast, speech_to_text, and flutter_dynamic_icon excluded (avoids v1 embedding compile errors)"
  fi
fi

# GeneratedPluginRegistrant.java is generated by flutter pub get and still references excluded plugins.
# Remove the try-catch blocks for flutter_native_splash, fluttertoast, speech_to_text (process bottom-to-top).
REGISTRANT="android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java"
if [ -f "$REGISTRANT" ]; then
  for plugin in SpeechToTextPlugin FlutterToastPlugin FlutterNativeSplashPlugin FlutterDynamicIconPlugin; do
    line=$(grep -n "$plugin" "$REGISTRANT" 2>/dev/null | head -1 | cut -d: -f1)
    while [ -n "$line" ]; do
      start=$((line - 2))
      end=$((line + 2))
      sed "${start},${end}d" "$REGISTRANT" > "${REGISTRANT}.tmp" && mv "${REGISTRANT}.tmp" "$REGISTRANT"
      line=$(grep -n "$plugin" "$REGISTRANT" 2>/dev/null | head -1 | cut -d: -f1)
    done
  done
  echo "  ✅ Removed excluded plugin registrations from GeneratedPluginRegistrant.java"
fi

# Fix flutter_app_badger
BADGER_FILE="$HOME/.pub-cache/hosted/pub.dev/flutter_app_badger-1.5.0/android/build.gradle"
if [ -f "$BADGER_FILE" ]; then
    if ! grep -q "namespace 'fr.g123k.flutterappbadge.flutterappbadger'" "$BADGER_FILE"; then
        echo "  ✅ Fixing flutter_app_badger..."
        sed -i '/^android {/a\    namespace '\''fr.g123k.flutterappbadge.flutterappbadger'\''' "$BADGER_FILE"
        echo "     Added namespace to flutter_app_badger"
    else
        echo "  ✓ flutter_app_badger already fixed"
    fi
else
    echo "  ⚠ flutter_app_badger not found (may not be installed)"
fi

# Fix flutter_dynamic_icon
DYNAMIC_ICON_FILE="$HOME/.pub-cache/hosted/pub.dev/flutter_dynamic_icon-2.1.0/android/build.gradle"
if [ -f "$DYNAMIC_ICON_FILE" ]; then
    if ! grep -q "namespace 'io.github.tastelessjolt.flutterdynamicicon'" "$DYNAMIC_ICON_FILE"; then
        echo "  ✅ Fixing flutter_dynamic_icon..."
        sed -i '/^android {/a\    namespace '\''io.github.tastelessjolt.flutterdynamicicon'\''' "$DYNAMIC_ICON_FILE"
        echo "     Added namespace to flutter_dynamic_icon"
    else
        echo "  ✓ flutter_dynamic_icon already fixed"
    fi
else
    echo "  ⚠ flutter_dynamic_icon not found (may not be installed)"
fi

# Fix flutter_dynamic_icon v1 embedding issue
# The registerWith method references PluginRegistry.Registrar which was removed in Flutter 3.24+
# Use Python for reliable multi-line removal instead of fragile sed
DYNAMIC_ICON_PLUGIN_FILE="$HOME/.pub-cache/hosted/pub.dev/flutter_dynamic_icon-2.1.0/android/src/main/java/io/github/tastelessjolt/flutterdynamicicon/FlutterDynamicIconPlugin.java"
if [ -f "$DYNAMIC_ICON_PLUGIN_FILE" ]; then
    if grep -q "public static void registerWith" "$DYNAMIC_ICON_PLUGIN_FILE"; then
        echo "  ✅ Fixing flutter_dynamic_icon v1 embedding issue..."
        python3 -c "
import re, sys
with open(sys.argv[1], 'r') as f:
    content = f.read()
# Remove @SuppressWarnings + registerWith method (handles multi-line braces)
content = re.sub(
    r'\s*@SuppressWarnings\s*\(\s*\"deprecation\"\s*\)\s*\n\s*public\s+static\s+void\s+registerWith\s*\([^)]*\)\s*\{[^}]*\}',
    '',
    content
)
# Also remove standalone registerWith without @SuppressWarnings
content = re.sub(
    r'\s*public\s+static\s+void\s+registerWith\s*\([^)]*\)\s*\{[^}]*\}',
    '',
    content
)
with open(sys.argv[1], 'w') as f:
    f.write(content)
" "$DYNAMIC_ICON_PLUGIN_FILE"
        echo "     Removed deprecated v1 embedding registerWith method"
    else
        echo "  ✓ flutter_dynamic_icon v1 embedding already fixed"
    fi
else
    echo "  ⚠ flutter_dynamic_icon plugin file not found"
fi

echo "✨ Done! You can now try building your app."
