// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pVVQ32u1RMGnJMTcpB1zkT-HzY2wUF0',
    appId: '1:40382368681:web:7888611335ad6449d9d2b8',
    messagingSenderId: '40382368681',
    projectId: 'swadkerala-fd498',
    authDomain: 'swadkerala-fd498.firebaseapp.com',
    storageBucket: 'swadkerala-fd498.firebasestorage.app',
    measurementId: 'G-ZB925SB1PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7FC12ebbtGTJohlbDCwenN6Qm8LpkXp0',
    appId: '1:40382368681:android:f0e74ab29e052e19d9d2b8',
    messagingSenderId: '40382368681',
    projectId: 'swadkerala-fd498',
    storageBucket: 'swadkerala-fd498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UjswzwM5gD4j8ux7MgMnVV7ElUObJfw',
    appId: '1:40382368681:ios:448632d1001b0bbed9d2b8',
    messagingSenderId: '40382368681',
    projectId: 'swadkerala-fd498',
    storageBucket: 'swadkerala-fd498.firebasestorage.app',
    iosBundleId: 'com.Swadkerala.Swadkerala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UjswzwM5gD4j8ux7MgMnVV7ElUObJfw',
    appId: '1:40382368681:ios:ee84e76e0bf2d1b2d9d2b8',
    messagingSenderId: '40382368681',
    projectId: 'swadkerala-fd498',
    storageBucket: 'swadkerala-fd498.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-pVVQ32u1RMGnJMTcpB1zkT-HzY2wUF0',
    appId: '1:40382368681:web:53fe77ba261bd7ded9d2b8',
    messagingSenderId: '40382368681',
    projectId: 'swadkerala-fd498',
    authDomain: 'swadkerala-fd498.firebaseapp.com',
    storageBucket: 'swadkerala-fd498.firebasestorage.app',
    measurementId: 'G-WX1F15Q44L',
  );
}
