name: Flutter Build CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (universal)
        run: flutter build apk --release

      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK & AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-builds
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
