package io.flutter.plugins

import androidx.annotation.Keep
import androidx.annotation.NonNull
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    
    @JvmStatic
    fun registerWith(@NonNull flutterEngine: FlutterEngine) {
        try {
            flutterEngine.plugins.add(com.llfbandit.app_links.AppLinksPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin app_links, com.llfbandit.app_links.AppLinksPlugin", e)
        }
        try {
            flutterEngine.plugins.add(dev.fluttercommunity.plus.connectivity.ConnectivityPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin connectivity_plus, dev.fluttercommunity.plus.connectivity.ConnectivityPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.firebase.analytics.FlutterFirebaseAnalyticsPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin firebase_analytics, io.flutter.plugins.firebase.analytics.FlutterFirebaseAnalyticsPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin firebase_core, io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin firebase_crashlytics, io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin firebase_messaging, io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin firebase_remote_config, io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin flutter_local_notifications, com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin", e)
        }
        try {
            flutterEngine.plugins.add(de.ffuf.in_app_update.InAppUpdatePlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin in_app_update, de.ffuf.in_app_update.InAppUpdatePlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.amorenew.mobile_number.MobileNumberPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin mobile_number, com.amorenew.mobile_number.MobileNumberPlugin", e)
        }
        try {
            flutterEngine.plugins.add(dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin package_info_plus, dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.pathprovider.PathProviderPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.baseflow.permissionhandler.PermissionHandlerPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin permission_handler_android, com.baseflow.permissionhandler.PermissionHandlerPlugin", e)
        }
        try {
            flutterEngine.plugins.add(net.nfet.flutter.printing.PrintingPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin printing, net.nfet.flutter.printing.PrintingPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.razorpay.razorpay_flutter.RazorpayFlutterPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin razorpay_flutter, com.razorpay.razorpay_flutter.RazorpayFlutterPlugin", e)
        }
        try {
            flutterEngine.plugins.add(dev.fluttercommunity.plus.share.SharePlusPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin share_plus, dev.fluttercommunity.plus.share.SharePlusPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.jaumard.smsautofill.SmsAutoFillPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin sms_autofill, com.jaumard.smsautofill.SmsAutoFillPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.urllauncher.UrlLauncherPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin url_launcher_android, io.flutter.plugins.urllauncher.UrlLauncherPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.baseflow.geolocator.GeolocatorPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin geolocator_android, com.baseflow.geolocator.GeolocatorPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.baseflow.geocoding.GeocodingPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin geocoding_android, com.baseflow.geocoding.GeocodingPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.flutter.plugins.googlesignin.GoogleSignInPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin google_sign_in_android, io.flutter.plugins.googlesignin.GoogleSignInPlugin", e)
        }
        try {
            flutterEngine.plugins.add(fr.g123k.flutterappbadger.FlutterAppBadgerPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin flutter_app_badger, fr.g123k.flutterappbadger.FlutterAppBadgerPlugin", e)
        }
        try {
            flutterEngine.plugins.add(io.github.tastelessjolt.flutterdynamicicon.FlutterDynamicIconPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin flutter_dynamic_icon, io.github.tastelessjolt.flutterdynamicicon.FlutterDynamicIconPlugin", e)
        }
        try {
            flutterEngine.plugins.add(com.csdcorp.speech_to_text.SpeechToTextPlugin())
        } catch (e: Exception) {
            Log.e(TAG, "Error registering plugin speech_to_text, com.csdcorp.speech_to_text.SpeechToTextPlugin", e)
        }
    }
}